export const Events = {
  EXT_FORM_SENT: "EXT_FORM_SENT",
  EXT_FORM_SENT_CUSTOM: "EXT_FORM_SENT_CUSTOM",
  EXT_LOGIN_SENT: "EXT_LOGIN_SENT",
  EXT_BUTTON_CLICK: "EXT_BUTTON_CLICK",
  UPDATE_AUTH_TOKEN: "UPDATE_AUTH_TOKEN",
}

